### ISSUE TITLE
GF version of Marmelad TTF breaks in Illustrator

### ISSUE THREAD

**Issue by alexeiva** [cyrealtype/Marmelad-Cyrillic#3]
From a user report: 

Illustrator CC2021 — CC2022:
![unnamed](https://user-images.githubusercontent.com/16634089/147114745-3c4239e6-dbd2-45ed-a719-60509b09f7b3.png)

Others apps render the font fine:
![unnamed-2](https://user-images.githubusercontent.com/16634089/147114787-8ff2da88-35ec-447d-9226-dcab944a93bd.png)

The ttf version from github works fine in Illustrator.
Illustrator + autohint bug?

**Comment by thlinard** [comment]
The issue can be observed with version 1.000.

[PR #445](https://github.com/google/fonts/pull/445) (version 1.100) never went into production, the GF API version is still 1.000.

**Comment by alexeiva** [comment]
fixed in https://github.com/cyrealtype/Marmelad-Cyrillic/pull/4
