### ISSUE TITLE
Reduced spacing for non-Russian letters with tails

### ISSUE THREAD

**Issue by alkaitagi** [cyrealtype/Marmelad-Cyrillic#5]
Thank you for the font! Just noticed that the tailed letters from other Cyrillic alphabets do not gain additional width. This is a problem because their tail is then not as prominent as that of e.g. `Ц` or `Щ`.

Leaving the link to [Google Fonts](https://fonts.google.com/specimen/Marmelad?preview.text=%D2%B3%D1%89%D1%86%D2%9B%D1%88) with the demo text.
<img width="501" alt="image" src="https://github.com/cyrealtype/Marmelad-Cyrillic/assets/32439229/d7a2d428-4e7a-4504-9db8-ecb23180cbc6">

**Comment by alexeiva** [comment]
fixed here: https://github.com/cyrealtype/Marmelad-Cyrillic/tree/master/fonts
